### PR TITLE
Newsweek site clone

### PR DESCRIPTION
**Pull request by diamond-nicholas**
### **What we have done**

-Added navigation bar and footer for the mobile screen, tablet screen
-Added content for the mobile, tablet, and desktop screens.
-Added some styles to using sass

### **What we used**
-HTML5
- CSS3
- BOOTSTRAP

### CODE REVIEW

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Changes Required

### Hi team :wave: 

Your project is coming along well. But there are some changes we have to make :hugs: 

- [ ] You have written good descriptive commit messages and pull request comment, but you missed updating your readme file, endeavor to do so, before submitting for next review, for a more professional repository.
- [ ] Also, you have linting issue, kindly correct them.
- [ ] For **large screen sizes**, before you scroll through, the Newsweek logo should be placed at the center.
- [ ] For **large screen sizes** you missed the **time and date** at the top left corner of the navigation bar, kindly add it.
- [ ] For **large screen sizes** you missed adding the **nav links** in the navigation section.
- [ ] For all the media screen sizes, the container wrapping the main section should have a **max width of 100%**  At least on my screen, doing this removed the extra white spaces, at these screen sizes.
- [ ] Style the **opinions section** better for large screen size to look like the original page, start 
  with the font- size.
- [ ] **My Turn, Culture & Travel and More stories** section needs to be styled properly. To achieve this, these sections, which are at the center of the website, needs more width, this would correct the characters being compacted. You can achieve this by reducing the width of the section on both ends of the website. 
- [ ] For large screen size, fill in the empty spaces with the required image cards.
- [ ] For medium screen size, the section on the right should have more width, this would give room for the characters to be properly spaced for the screen size.
- [ ] At medium screen size, my opinion section is also not looking good. kindly reference the original [website](https://www.newsweek.com/) 
- [ ] For a more semantic HTML file, the footer section should be wrapped within the **footer tag**; also, the sections between the navigation and footer should be wrapped with a **main tag**
- [ ] Format the footer section of your HTML file properly, in your text editor .

### Always refer to the original [website](https://www.newsweek.com/)

That is it, implement the required changes, then submit another form for a code review.

If you need clarifications, you can reachout on Slack @ **Inyama, Uchechukwu Henry**

### ``` Have a great day ``` :slightly_smiling_face: 

``` Uchechukwu Henry Inyama ```

**Review by PhillipUg — CHANGES_REQUESTED** [review]
Hey team, 👋

You have done an amazing job implementing the project requirements of this project.

However, there are still some changes 👇 you need to implement to approve this request 🔍

### Changes Required ♻️ 

- [ ] I am unable to open your page using the live link in your README file.
- [ ] You have some linter errors. Please fix them

- [ ] Please work on all the changes requested by the previous reviewer


#### Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack as **Phillip Musiime**
I would be happy to help! 👩‍💻 

Happy coding 🤓

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
## Status: Changes Required :recycle: 
Hello @diamond-nicholas @Paul-Clue. I believe you need to take your time and re-work on the project. The layout is there and it is a good start. However, before moving on, there is a lot to do. :unamused: 

I am giving two pictures of your site how it looks now and giving you the requirements to pass this task. Please refer to them one by one.
screen
screen2

- [ ] Your page overlaps for mobile view, and there is a huge empty space for the laptop view.
### Requirements
* [ ] It contains Newsweek logo 
* [ ] It contains a date in the same format on the source page 
* [ ] It contains Sign in and Subscribe links 
* [ ] It contains main navigation links 
* [ ] **It changes with RWD breakpoints** 

* [ ] It contains `Featured stories` section
* [ ] It contains `Top story` section 
* [ ] It contains `Opinion` section 
* [ ] It contains `Latest news` section 
* [ ] It contains `More stories` section 
* [ ] It contains `In the magazine` section 
* [ ] It contains `Editor's picks` section 
* [ ] It contains `Featured slideshows` section 
* [ ] **It changes with RWD breakpoints** 

* [ ] It contains Newsweek logo 
* [ ] It contains social media icons 
* [ ] It contains main navigation links 
* [ ] **It changes with RWD breakpoints** 

You have nicely configured the linters and your commit messages are imperative, which is nice. :muscle: .You should try to mimic the page, you need to decrease the total width of the screen as the original page. There shouldn't be any empty area, and you need to satisfy the conditions listed above. You need to take care of the responsiveness, and for this, you should follow the design layout from the original page. While doing these tasks, please use bootstrap. Also in your Readme, at the license section, there is a broken image. Please fix this. Don't rush and take your time, when you feel your page looks like the original page, submit for a re-review.
If you have any question about the review, feel free to reach me via Slack. :100: 
_Eyüp Sercan UYGUR_

**Review by umairarshadbutt — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @diamond-nicholas and @Paul-Clue 
Good job with the changes! :tada: We are almost there.
We, however, do have a few changes to carry out before we proceed (see review comment).

##

Kindly work on the suggested changes  👇.
- [ ] Please Fix the linters issue
- [ ] Please implement the previous TSE suggestion
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:

**[OPTIONAL]** Please work on Navbar before the merge
|[Source Page](https://www.newsweek.com/)|[Clone Page](https://rawcdn.githack.com/icebox827/Newsweek-copy/821d25472f110dc58c679af63798d59747898224/index.html)|
|:---:|:---:|
|source-page|clone|


##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
